apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: flask-app
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      tier: database
  template:
    metadata:
      labels:
        app: flask-app
        tier: database
    spec:
      containers:
      - name: postgres-db
        image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: POSTGRES_PASSWORD
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        emptyDir: {}
