apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: flask-app
    tier: database
spec:
  selector:
    app: flask-app
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None  # This ensures it's only accessible within the cluster
