apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: flask-app
    tier: database
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy  # base64 encoded value of "myuser"
  POSTGRES_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==  # base64 encoded value of "mysecretpassword"
  POSTGRES_DB: bXlkYXRhYmFzZQ==  # base64 encoded value of "mydatabase"
