apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded value of "postgres"
  POSTGRES_PASSWORD: bXlzZWN1cmVwYXNzd29yZA==  # base64 encoded value of "mysecurepassword"
  POSTGRES_DB: cG9zdGdyZXM=  # base64 encoded value of "postgres"